coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 5%

fixes:
  - "src/::packages/widget/src/"
  - "src/::packages/game-sdk/src/"

flags:
  widget:
    paths:
      - packages/widget/
  game-sdk:
    paths:
      - packages/game-sdk/

comment:
  layout: reach,diff,flags,files
  behavior: default
